//LOGIN ACTIONS


//AUTH ACTIONS


//REGISTER ACTIONS



//EVENT ACTIONS
export const NEW_IMAGE_TO_STORE = 'NEW_IMAGE_TO_STORE';
export const CLEAR_IMAGE_STORE = 'CLEAR_IMAGE_STORE';

//FRECKLE ACTIONS
export const ADD_FRECKLE_COUNT = 'ADD_FRECKLE_COUNT';
export const CLEANUP_FRECKLE = 'CLEANUP_FRECKLE';

//TUMOR ACTIONS
export const CHANGE_TUMOR_DIMENSIONS = 'CHANGE_TUMOR_DIMENSIONS';
export const CLEANUP_TUMOR = 'CLEANUP_TUMOR';

//MARKER ACTIONS
export const ADD_MARKER = 'ADD_MARKER';
export const CLEANUP_MARKER = 'CLEANUP_MARKER';
export const CHANGE_MARKER_MENU = 'CHANGE_MARKER_MENU';
export const CHANGE_MARKER_LOCATION = 'CHANGE_MARKER_LOCATION';
export const CHANGE_MARKER_TYPE = 'CHANGE_MARKER_TYPE';