//LOGIN ACTIONS



//AUTH ACTIONS



//REGISTER ACTIONS



//EVENT ACTIONS
export const CLEANUP_EVENT = 'CLEANUP_EVENT';
export const CHANGE_EVENT_INFO = 'CHANGE_EVENT_INFO';
export const SUBMIT_EVENT = 'SUBMIT_EVENT';

//FRECKLE ACTIONS
export const ADD_FRECKLE_COUNT = 'ADD_FRECKLE_COUNT';
export const CLEANUP_FRECKLE = 'CLEANUP_FRECKLE';

//TUMOR ACTIONS
export const CHANGE_TUMOR_DIMENSIONS = 'CHANGE_TUMOR_DIMENSIONS';
export const CLEANUP_TUMOR = 'CLEANUP_TUMOR';

//MARKER ACTIONS
export const ADD_MARKER = 'ADD_MARKER';
export const CLEANUP_MARKER = 'CLEANUP_MARKER';
export const CHANGE_MARKER_MENU = 'CHANGE_MARKER_MENU';
export const CHANGE_MARKER_LOCATION = 'CHANGE_MARKER_LOCATION';
export const CHANGE_MARKER_TYPE = 'CHANGE_MARKER_TYPE';

//BODY LOCATION ACTIONS
export const CHANGE_BODY_LOCATION = 'CHANGE_BODY_LOCATION';
export const CLEANUP_LOCATION = 'CLEANUP_LOCATION';