//LOGIN ACTIONS


//AUTH ACTIONS


//REGISTER ACTIONS



//EVENT ACTIONS
export const NEW_IMAGE_TO_STORE = 'NEW_IMAGE_TO_STORE';
export const CLEAR_IMAGE_STORE = 'CLEAR_IMAGE_STORE';

//MARKER ACTIONS
export const ADD_MARKER = 'ADD_MARKER';
export const CLEANUP_MARKER = 'CLEANUP_MARKER';
export const CHANGE_MARKER_MENU = 'CHANGE_MARKER_MENU';
export const CHANGE_MARKER_LOCATION = 'CHANGE_MARKER_LOCATION';